test(settings): Isolation w/ frontend_domain None
Workaround a test fixture isolation issue where the `IVoltoSettings.frontend_domain`
setting has a value of `None` by changing the `plone.volto.patches.construct_url` patch
to properly handle that value.

I found under local development that there were errors in the
`plone.restapi.tests.test_services_users` tests when running the whole suite with `$
./bin/test -s plone.restapi` but not when running only those tests with `$ ./bin/test -s
plone.restapi -m plone.restapi.tests.test_services_users`:

    Failure in test test_add_anon_user_sends_properties_are_saved (plone.restapi.tests.test_services_users.T
    Current directory is /home/rpatterson/src/plone/volto/api/
    estUsersEndpoint)
    Traceback (most recent call last):
      File "/usr/lib/python3.9/unittest/case.py", line 59, in testPartExecutor
        yield
      File "/usr/lib/python3.9/unittest/case.py", line 592, in run
        self._callTestMethod(testMethod)
      File "/usr/lib/python3.9/unittest/case.py", line 550, in _callTestMethod
        method()
      File "/home/rpatterson/src/plone/volto/api/src/plone.restapi/src/plone/restapi/tests/test_services_users.py", line 242, in test_add_anon_user_sends_properties_are_saved
        self.assertEqual(201, response.status_code)
      File "/usr/lib/python3.9/unittest/case.py", line 837, in assertEqual
        assertion_func(first, second, msg=msg)
      File "/usr/lib/python3.9/unittest/case.py", line 830, in _baseAssertEqual
        raise self.failureException(msg)
    AssertionError: 201 != 500

        457/555 (82.3%)

    Failure in test test_add_user_with_sendPasswordRest_sends_email (plone.restapi.tests.test_services_users.TestUsersEndpoint)
    Traceback (most recent call last):
      File "/usr/lib/python3.9/unittest/case.py", line 59, in testPartExecutor
        yield
      File "/usr/lib/python3.9/unittest/case.py", line 592, in run
        self._callTestMethod(testMethod)
      File "/usr/lib/python3.9/unittest/case.py", line 550, in _callTestMethod
        method()
      File "/home/rpatterson/src/plone/volto/api/src/plone.restapi/src/plone/restapi/tests/test_services_users.py", line 204, in test_add_user_with_sendPasswordRest_sends_email
        self.assertEqual(201, response.status_code)
      File "/usr/lib/python3.9/unittest/case.py", line 837, in assertEqual
        assertion_func(first, second, msg=msg)
      File "/usr/lib/python3.9/unittest/case.py", line 830, in _baseAssertEqual
        raise self.failureException(msg)
    AssertionError: 201 != 500

        460/555 (82.9%)

    Failure in test test_anonymous_requires_enable_self_reg (plone.restapi.tests.test_services_users.TestUsersEndpoint)
    Traceback (most recent call last):
      File "/usr/lib/python3.9/unittest/case.py", line 59, in testPartExecutor
        yield
      File "/usr/lib/python3.9/unittest/case.py", line 592, in run
        self._callTestMethod(testMethod)
      File "/usr/lib/python3.9/unittest/case.py", line 550, in _callTestMethod
        method()
      File "/home/rpatterson/src/plone/volto/api/src/plone.restapi/src/plone/restapi/tests/test_services_users.py", line 809, in test_anonymous_requires_enable_self_reg
        self.assertEqual(201, response.status_code)
      File "/usr/lib/python3.9/unittest/case.py", line 837, in assertEqual
        assertion_func(first, second, msg=msg)
      File "/usr/lib/python3.9/unittest/case.py", line 830, in _baseAssertEqual
        raise self.failureException(msg)
    AssertionError: 201 != 500

        464/555 (83.6%)

    Failure in test test_anonymous_without_enable_user_pwd_choice_sends_mail (plone.restapi.tests.test_services_users.TestUsersEndpoint)
    Traceback (most recent call last):
      File "/usr/lib/python3.9/unittest/case.py", line 59, in testPartExecutor
        yield
      File "/usr/lib/python3.9/unittest/case.py", line 592, in run
        self._callTestMethod(testMethod)
      File "/usr/lib/python3.9/unittest/case.py", line 550, in _callTestMethod
        method()
      File "/home/rpatterson/src/plone/volto/api/src/plone.restapi/src/plone/restapi/tests/test_services_users.py", line 822, in test_anonymous_without_enable_user_pwd_choice_sends_mail
        self.assertEqual(201, response.status_code)
      File "/usr/lib/python3.9/unittest/case.py", line 837, in assertEqual
        assertion_func(first, second, msg=msg)
      File "/usr/lib/python3.9/unittest/case.py", line 830, in _baseAssertEqual
        raise self.failureException(msg)
    AssertionError: 201 != 500

        495/555 (89.2%)

    Failure in test test_user_requests_password_sends_password_via_mail (plone.restapi.tests.test_services_users.TestUsersEndpoint)
    Traceback (most recent call last):
      File "/usr/lib/python3.9/unittest/case.py", line 59, in testPartExecutor
        yield
      File "/usr/lib/python3.9/unittest/case.py", line 592, in run
        self._callTestMethod(testMethod)
      File "/usr/lib/python3.9/unittest/case.py", line 550, in _callTestMethod
        method()
      File "/home/rpatterson/src/plone/volto/api/src/plone.restapi/src/plone/restapi/tests/test_services_users.py", line 601, in test_user_requests_password_sends_password_via_mail
        self.assertEqual(response.status_code, 200)
      File "/usr/lib/python3.9/unittest/case.py", line 837, in assertEqual
        assertion_func(first, second, msg=msg)
      File "/usr/lib/python3.9/unittest/case.py", line 830, in _baseAssertEqual
        raise self.failureException(msg)
    AssertionError: 500 != 200

Trying to get good debugging information from those failures was quite the chore, I
think we need a better `pdb.post_mortem()` story when using the
`plone.testing.z2.ZSERVER_FIXTURE` layer.  I ended up modifying
`ZPublisher.WSGIPublisher.publish_module(...)` locally to wrap the `_publish(...)` call
in a `try` clause with `pdb.post_mortem()` in the `except` block.

At any rate, the most important issue here is obviously some sort of isolation issue.
We should prioritize working towards a reality in which a test never passes, fails, or
errors because of *how* it was run.  The more tests become a nest of special
incantations, known issues, rubber chicken waving, and other lore passed around between
developers (inevitably the more senior developers), the more they are experienced as a
dogmatic obstacle to development that developers hate instead of a tool that makes
writing code more efficient and less uncertain that developers love.  Having said that,
I haven't yet put into the time to chase down the core isolation issue.

In the meantime, the "symptom" exception behind these specific errors does seem like it
comes from a case the code should handle.  Specifically, I assume the intention here was
to use the `default` argument to `getattr(...)` to avoid an empty value.  In the case
when all the tests are run, however, this setting has a value of `None` which defeats
this purpose:

    AttributeError: 'NoneType' object has no attribute 'endswith'

     - Expression: "python:view.construct_url(reset['randomstring'])+'?userid='+member.getUserName()"
     - Filename:   ... ne/browser/login/templates/registered_notify_template.pt
     - Location:   (line 21: col 48)
     - Source:     ... python:view.construct_url(reset['randomstring'])+'?userid='+member.getUserName() ...
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     - Arguments:  template: <Products.Five.browser.pagetemplatefile.ViewPageTemplateFile object at 0x7f6ea01581c0>
                   options: {'member': <Products.PlonePAS.tools.memberdata.MemberData object at 0x7f6e9f415580>, 'reset': {'randomstring': '6ef4c60fae43411394ea738744708126', 'expires': datetime.datetime(2022, 1, 1, 19, 34, 25, 661749), 'userid': 'howard'}, 'email': 'howard.zinn@example.com', 'charset': 'utf-8'}
                   args: ()
                   nothing: None
                   modules: <Products.PageTemplates.ZRPythonExpr._SecureModuleImporter object at 0x7f6ea73d7df0>
                   request: <WSGIRequest, URL=http://localhost:42255/plone/@users>
                   view: <Products.Five.browser.metaconfigure.SimpleViewClass from ./eggs/Products.CMFPlone-5.2.6-py3.9.egg/Products/CMFPlone/browser/login/templates/registered_notify_template.pt object at 0x7f6e9f6928b0>
                   context: <RegistrationTool at /plone/portal_registration>
                   views: <Products.Five.browser.pagetemplatefile.ViewMapper object at 0x7f6e9f77ab50>
                   here: <RegistrationTool at /plone/portal_registration>
                   container: <RegistrationTool at /plone/portal_registration>
                   root: <Application at >
                   traverse_subpath: []
                   user: <SpecialUser 'Anonymous User'>
                   default: <DEFAULT>
                   repeat: <Products.PageTemplates.engine.RepeatDictWrapper object at 0x7f6e8ef27840>
                   loop: {}
                   target_language: None
                   translate: <function BaseTemplate.render.<locals>.translate at 0x7f6e8ea423a0>
                   attrs: {}
                   lt: '<'
                   gt: '>'
                   member: <Products.PlonePAS.tools.memberdata.MemberData object at 0x7f6e9f415580>
                   reset: {'randomstring': '6ef4c60fae43411394ea738744708126', 'expires': datetime.datetime(2022, 1, 1, 19, 34, 25, 661749), 'userid': 'howard'}
                   email_from_name: None
                   fullname: 'Howard Zinn'

So this fix seems appropriate regardless of the isolation issue.